### ISSUE TITLE
Why the key point feature is a three-channel color map?

### ISSUE THREAD

**Issue by yzew** [amathislab/BUCTD#11]
Hi, may I ask why three channels are used for the key point features entered here? Is there any basis for the selection of different keypoint colors?

**Comment by zhoumu53** [comment]
Hi, we tested several types of keypoint features, e.g. 3-channel (rgb) keypoints heatmap, 1-channel (gray-scale) keypoints  heatmap and the N-channel heatmap, the performance of 3-channel heatmaps is slightly better than the others, therefore we keep this type of heatmap.
The idea of using 3-channel (rgb) keypoints heatmap is to provide enough semantic information of each body part. Therefore, you can define the color by your own -- but just keep in mind make them consistent during training and inference.
