### ISSUE TITLE
About code training

### ISSUE THREAD

**Issue by wuhuqifei0** [amathislab/BUCTD#12]
I am a beginner in human pose estimation, and I cannot find the script named "train_BUCTD_synthesis_noise.sh". What command should I use to train this code? Could you provide an example command?

**Comment by zhoumu53** [comment]
Sorry for the confusing in the tutorial - you can use: train_BUCTD_COAM_gen_sample.sh, please check this [script](https://github.com/amathislab/BUCTD/blob/main/scripts/train/train_BUCTD_COAM_gen_sample.sh) instead.
