### ISSUE TITLE
Testing videos using pre-trained models

### ISSUE THREAD

**Issue by felipearrudamoura** [amathislab/BUCTD#13]
Hello,

I would like to run the BUTCD in videos using your pre-trained models. I just did not get the instructions for that.
Can you help me?

Regards,

Felipe.

**Comment by zhoumu53** [comment]
Hi, we provided the inference script [here](https://github.com/amathislab/BUCTD/blob/inference_w_vis/tools/inference.py). You can run inference with the pretrained weights by feeding the video frames as well as the predictions from other BU models.

**Comment by AlexEMG** [comment]
Please also note that BUCTD will be integrated in DLC3 --> https://github.com/DeepLabCut/DeepLabCut

**Comment by felipearrudamoura** [comment]
Thanks, AlexEMG. Do you have an idea when DLC3 will be released?

**Comment by felipearrudamoura** [comment]
> Hi, we provided the inference script [here](https://github.com/amathislab/BUCTD/blob/inference_w_vis/tools/inference.py). You can run inference with the pretrained weights by feeding the video frames as well as the predictions from other BU models.

It seems that this link is not active anymore. Do you have any update?
