### ISSUE TITLE
How to get the "train_cond.json"？

### ISSUE THREAD

**Issue by yzew** [amathislab/BUCTD#14]
When I run the "train_BUCTD_prenet_gen_sample.sh", I found that I couldn't simply use “person_keypoints_train2017.json”。So how to get the "train_cond.json"？Can you provide the json file for training CTD on coco dataset? Looking forward to your reply!

**Comment by zhoumu53** [comment]
Sure, we put the data [here](https://zenodo.org/records/10039883).

**Comment by yzew** [comment]
> Sure, we put the data [here](https://zenodo.org/records/10039883).

Thank you very much!!

**Comment by LucZot** [comment]
@yzew alternatively, you can now also train a CTD model with generative sampling on the original train.json file (updated by https://github.com/amathislab/BUCTD/pull/19)
