### ISSUE TITLE
CTD-preNet-W32's model

### ISSUE THREAD

**Issue by yzew** [amathislab/BUCTD#15]
I find that only BUCTD-preNet-W48's model Weights are available in the repository. Can you provide BUCTD-preNet-W32's model on COCO? I want to compare with your prenet-w32 model on the COCO dataset, but didn't have the time to train it again with your methods.

**Comment by zhoumu53** [comment]
Hi, thank you for your attention. And sorry for this, we only trained the model BUCTD-preNet-W48 on *COCO* which is available online.
