### ISSUE TITLE
Regarding environment configuration

### ISSUE THREAD

**Issue by dezhu-zhao** [amathislab/BUCTD#16]
Hi, may I ask if this code can run on Windows and a CPU? When configuring the environment, I encounter many errors when installing dependencies, and it eventually shows "make: *** No rule to make target 'install'. Stop". Therefore, I am considering using a Windows CPU to run it and would like to know if that is possible.

**Comment by AlexEMG** [comment]
I do think I could run it on Windows, but we have not tested it ourselves. Please note that in Windows you can also use Ubuntu as a subsystem: https://ubuntu.com/desktop/wsl -- that might greatly simplify your installation process. 

Regarding the CPU, that's fine of course, it's just much slower than a GPU.

**Comment by dezhu-zhao** [comment]
Thank you very much for your response, I will try to set up an Ubuntu subsystem to run the code.
