### ISSUE TITLE
install requirement packages lshashing==1.1.3 encounter error "NameError: name 'ext_modules' is not defined"

### ISSUE THREAD

**Issue by chenhzhu** [amathislab/BUCTD#17]
Hi, I encountered error when try to install packages inside my conda env (env created with python==3.8.10). I download numpy first then run the pip install.

Thanks for your help.

PC info:
OS: Win11, running code in WSL Ubuntu
CPU: Intel i7-10700F CPU 2.90GHz

After run `pip install -r requirement.txt`, error looks like this:
![image](https://github.com/amathislab/BUCTD/assets/143351635/4146673b-18ee-4e8d-9abf-2a491be2a22c)

Full text version:
pip install -r requirements.txt
Collecting asttokens==2.0.5 (from -r requirements.txt (line 1))
  Using cached asttokens-2.0.5-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting backcall==0.2.0 (from -r requirements.txt (line 2))
  Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting certifi==2023.7.22 (from -r requirements.txt (line 3))
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer==3.3.0 (from -r requirements.txt (line 4))
  Using cached charset_normalizer-3.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (32 kB)
Collecting click==8.1.2 (from -r requirements.txt (line 5))
  Using cached click-8.1.2-py3-none-any.whl.metadata (3.2 kB)
Collecting colour==0.1.5 (from -r requirements.txt (line 6))
  Using cached colour-0.1.5-py2.py3-none-any.whl.metadata (18 kB)
Collecting cycler==0.11.0 (from -r requirements.txt (line 7))
  Using cached cycler-0.11.0-py3-none-any.whl.metadata (785 bytes)
Collecting Cython==0.29.28 (from -r requirements.txt (line 8))
  Using cached Cython-0.29.28-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (2.8 kB)
Collecting debugpy==1.6.0 (from -r requirements.txt (line 9))
  Using cached debugpy-1.6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (1.1 kB)
Collecting decorator==5.1.1 (from -r requirements.txt (line 10))
  Using cached decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
Collecting docopt==0.6.2 (from -r requirements.txt (line 11))
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting easydict==1.7 (from -r requirements.txt (line 12))
  Using cached easydict-1.7.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... done
Collecting entrypoints==0.4 (from -r requirements.txt (line 13))
  Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
Collecting executing==0.8.3 (from -r requirements.txt (line 14))
  Using cached executing-0.8.3-py2.py3-none-any.whl.metadata (8.6 kB)
Collecting Flask==2.1.1 (from -r requirements.txt (line 15))
  Using cached Flask-2.1.1-py3-none-any.whl.metadata (3.9 kB)
Collecting fonttools==4.33.2 (from -r requirements.txt (line 16))
  Using cached fonttools-4.33.2-py3-none-any.whl.metadata (125 kB)
Collecting h5py==3.6.0 (from -r requirements.txt (line 17))
  Using cached h5py-3.6.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (1.9 kB)
Collecting idna==3.4 (from -r requirements.txt (line 18))
  Using cached idna-3.4-py3-none-any.whl.metadata (9.8 kB)
Collecting imageio==2.17.0 (from -r requirements.txt (line 19))
  Using cached imageio-2.17.0-py3-none-any.whl.metadata (4.8 kB)
Collecting importlib-metadata==4.11.3 (from -r requirements.txt (line 20))
  Using cached importlib_metadata-4.11.3-py3-none-any.whl.metadata (4.0 kB)
Collecting ipykernel==6.13.0 (from -r requirements.txt (line 21))
  Using cached ipykernel-6.13.0-py3-none-any.whl.metadata (2.4 kB)
Collecting ipython==8.2.0 (from -r requirements.txt (line 22))
  Using cached ipython-8.2.0-py3-none-any.whl.metadata (4.9 kB)
Collecting itsdangerous==2.1.2 (from -r requirements.txt (line 23))
  Using cached itsdangerous-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Collecting jedi==0.18.1 (from -r requirements.txt (line 24))
  Using cached jedi-0.18.1-py2.py3-none-any.whl.metadata (20 kB)
Collecting Jinja2==3.1.1 (from -r requirements.txt (line 25))
  Using cached Jinja2-3.1.1-py3-none-any.whl.metadata (3.5 kB)
Collecting joblib==1.1.0 (from -r requirements.txt (line 26))
  Using cached joblib-1.1.0-py2.py3-none-any.whl.metadata (5.2 kB)
Collecting json-tricks==3.15.5 (from -r requirements.txt (line 27))
  Using cached json_tricks-3.15.5-py2.py3-none-any.whl.metadata (17 kB)
Collecting jupyter-client==7.2.2 (from -r requirements.txt (line 28))
  Using cached jupyter_client-7.2.2-py3-none-any.whl.metadata (5.4 kB)
Collecting jupyter-core==4.10.0 (from -r requirements.txt (line 29))
  Using cached jupyter_core-4.10.0-py3-none-any.whl.metadata (1.4 kB)
Collecting kiwisolver==1.4.2 (from -r requirements.txt (line 30))
  Using cached kiwisolver-1.4.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting lshashing==1.1.3 (from -r requirements.txt (line 32))
  Using cached lshashing-1.1.3.tar.gz (122 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1aamtb6d/lshashing_d75e976c9a8d40aa971e6d6fb7a2b29c/setup.py", line 42, in <module>
          ext_modules = ext_modules
      NameError: name 'ext_modules' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zhoumu53** [comment]
Hello, I recommend temporarily removing lshashing from the _**requirements.txt**_ file to bypass the installation error. After that, you can proceed with installing the other packages. Meanwhile, check for a version of _lshashing_ that is compatible with your device and python environment.
