### ISSUE TITLE
Inquiry on Integration Timeline for BUCTD in DeepLabCut

### ISSUE THREAD

**Issue by ZackAXue** [amathislab/BUCTD#18]
Could you kindly share any available timelines or milestones regarding the integration of BUCTD into DeepLabCut? Understanding the expected rollout schedule will greatly benefit users like myself in planning upcoming research projects that could leverage this new functionality. 

Thank you for your support of the research community. Looking forward to your response!

**Comment by AlexEMG** [comment]
We think this will happen any day, hopefully before FENS at the end of June!

**Comment by AlexEMG** [comment]
A release candidate can be found here: https://github.com/DeepLabCut/DeepLabCut/issues/2616

Let us know how it goes!

**Comment by LucZot** [comment]
BUCTD is finally integrated into DLC3!  -> https://github.com/DeepLabCut/DeepLabCut/pull/2952
