### ISSUE TITLE
Questions about the OCHuman dataset results

### ISSUE THREAD

**Issue by lllluy** [amathislab/BUCTD#21]
Hi! This is a splendid work and thanks for releasing the code. 
I would like to know why your papers report low results on the OCHuman dataset? For example, MIPNet-W48 reported AP=74.1 in the original paper, but in your paper it becomes 42.0? Similar results were found for both CID and HRNet.

**Comment by LucZot** [comment]
Hi @lllluy, thanks for your interest in our work! Please note that MIPNet compares results using _ground-truth_ bounding boxes. To ensure a fair comparison with bottom-up models, we present results for top-down models (like MIPNet, HRNet, etc.) using bounding boxes from a detector (provided by the benchmark).
