### ISSUE TITLE
Questions about the CrowdPose dataset results with HRNet-W48

### ISSUE THREAD

**Issue by 1084281986** [amathislab/BUCTD#22]
Hi there,

Firstly, great work and thank you for sharing your results and code!

I noticed that your paper reports an AP of 67.3 using HRNet-W48 on the CrowdPose dataset, which is not covered in the original HRNet paper. I attempted to replicate this result by training HRNet-W48 on CrowdPose with an input size of 640 and a batch size of 8 for 210 epochs, but my results were significantly lower.

Could you please share the specific parameters and settings you used for training HRNet-W48 on CrowdPose to achieve the reported AP score?

**Comment by zhoumu53** [comment]
Hi, thank you for your interest! Basically, we didn't train the bottom-up models, and we only evaluate the performance based on the available checkpoints and the codebase. If you want to retrain the model and reproduce the results, please find the original [codebase](https://github.com/HRNet/HRNet-Bottom-Up-Pose-Estimation) of bottom-up HRNet.
