### ISSUE TITLE
Pretrained model keypoint number mismatch

### ISSUE THREAD

**Issue by Laudwika** [amathislab/BUCTD#5]
Hi, I'm trying to test the code, and while the coco config file and weights work well, there is a mismatch between the ochuman and crowdpose weights.

The OcHuman weights says their missing weights with 17 keypoints on the coco yaml

The CrowdPose weights say they are missing weights with 14 keypoints on the crowdpose yaml

Also, will there be plans to release an inference code to perform single image inference?

Thank you, I appreciate your work!

**Comment by zhoumu53** [comment]
Hi @Laudwika , thank you for your message, and sorry for the confusion. 

Please find out the weights for OCHuman [here](https://drive.google.com/file/d/1O7SqZi4u-a1kBi46ya2HS-RgoyWHNfl_/view?usp=share_link).

For CrowdPose, we will upload the correct checkpoint asap.

**Comment by AlexEMG** [comment]
Addressed in #6

**Comment by SHUOFEN2019416** [comment]
How to implement visualization? Thank you!

**Comment by AlexEMG** [comment]
@Laudwika, we updated the PR. You can also find all weights here: https://zenodo.org/records/10039883

@SHUOFEN2019416, please open a new PR for a new question. But yes, we can share code!
