### ISSUE TITLE
How to test on single image ?

### ISSUE THREAD

**Issue by ocracy** [amathislab/BUCTD#9]
Please give an example of given single image

**Comment by zhoumu53** [comment]
Please check [PR](https://github.com/amathislab/BUCTD/pull/10)

**Comment by ocracy** [comment]
Hello @zhoumu53  Thank you for your reply.

There is onyl test,train script

Could you please add one simple .py file to test on single image by downloading your pretrained model.

like this
image_path = 'file.jpg'
...
points = ...
